apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-configmmap
  {{- if .Values.annotations }}
  annotations: {{- include "tplvalues.render" ( dict "value" .Values.annotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  some.bs: "here"

