apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets
  {{- if .Values.annotations }}
  annotations: {{- include "tplvalues.render" ( dict "value" .Values.annotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  TOKEN: "some-bs-here"
